feat: use flarum 1.8.x, php8.3, alpine 3.21

diff --git a/rootfs/usr/local/bin/extension b/rootfs/usr/local/bin/extension
--- a/rootfs/usr/local/bin/extension
+++ b/rootfs/usr/local/bin/extension
@@ -8,7 +8,10 @@ CEND="${CSI}0m"
 CRED="${CSI}1;31m"
 CGREEN="${CSI}1;32m"
 
-cd /flarum/app
+cd /flarum/app || {
+  echo "[ERROR] Cannot cd to /flarum/app"
+  exit 1
+}
 
 # Composer cache dir and packages list paths
 CACHE_DIR=/flarum/app/extensions/.cache
@@ -18,6 +21,9 @@ LIST_FILE=/flarum/app/extensions/list
 action="${1}"
 package="${2}"
 
+UID=${UID:-$(id -u)}
+GID=${GID:-$(id -g)}
+
 # Create custom extensions cache folder and list file
 su-exec "${UID}:${GID}" mkdir -p "${CACHE_DIR}"
 su-exec "${UID}:${GID}" touch "${LIST_FILE}"
@@ -26,23 +32,25 @@ case "${action}" in
   # Install a flarum extension
   "require")
     COMPOSER_CACHE_DIR="${CACHE_DIR}" su-exec "${UID}:${GID}" composer require "${package}"
+    # shellcheck disable=SC2181
     if [ $? -eq 0 ]; then
       echo "${package}" >> "${LIST_FILE}"
-      echo -e "\n${CGREEN}${package} added to flarum.${CEND}"
+      printf "\n%s added to flarum.%s\n" "${CGREEN}${package}" "${CEND}"
       # Remove duplicate packages
       sort -u -o "${LIST_FILE}" "${LIST_FILE}"
     else
-      echo -e "\n${CRED}/!\ An error has occurred...${CEND}"
+      printf "\n%s/!\ An error has occurred...%s\n" "${CRED}" "${CEND}"
     fi
     ;;
   # Remove a flarum extension
   "remove")
     COMPOSER_CACHE_DIR="$CACHE_DIR" su-exec "${UID}:${GID}" composer remove "${package}"
+    # shellcheck disable=SC2181
     if [ $? -eq 0 ]; then
       sed -i "\|${package}|d" "$LIST_FILE"
-      echo -e "\n${CGREEN}${package} removed from flarum${CEND}"
+      printf "\n%s removed from flarum%s\n" "${CGREEN}${package}" "${CEND}"
     else
-      echo -e "\n${CRED}/!\ An error has occurred...${CEND}"
+      printf "\n%s/!\ An error has occurred...%s" "${CRED}" "${CEND}"
     fi
     ;;
   "list")
diff --git a/rootfs/usr/local/bin/startup b/rootfs/usr/local/bin/startup
--- a/rootfs/usr/local/bin/startup
+++ b/rootfs/usr/local/bin/startup
@@ -16,19 +16,33 @@ LIST_FILE=/flarum/app/extensions/list
 
 # Set file config for nginx and php
 sed -i "s/<FLARUM_PORT>/${FLARUM_PORT}/g" /etc/nginx/nginx.conf
-sed -i "s/<UPLOAD_MAX_SIZE>/${UPLOAD_MAX_SIZE}/g" /etc/nginx/nginx.conf /etc/php8/php-fpm.d/www.conf
-sed -i "s/<PHP_MEMORY_LIMIT>/${PHP_MEMORY_LIMIT}/g" /etc/php8/php-fpm.d/www.conf
-sed -i "s/<OPCACHE_MEMORY_LIMIT>/${OPCACHE_MEMORY_LIMIT}/g" /etc/php8/conf.d/00_opcache.ini
+sed -i "s/<UPLOAD_MAX_SIZE>/${UPLOAD_MAX_SIZE}/g" /etc/nginx/nginx.conf /etc/php83/php-fpm.d/www.conf
+sed -i "s/<PHP_MEMORY_LIMIT>/${PHP_MEMORY_LIMIT}/g" /etc/php83/php-fpm.d/www.conf
+sed -i "s/<OPCACHE_MEMORY_LIMIT>/${OPCACHE_MEMORY_LIMIT}/g" /etc/php83/conf.d/00_opcache.ini
 
-# Set permissions for /flarum folder
+UID=${UID:-$(id -u)}
+GID=${GID:-$(id -g)}
+
+# Set permissions for /flarum folder and other critical directories
 echo "[INFO] Setting folder permissions"
-for folder in /etc/s6.d /run/php /var/log /var/lib/nginx; do
-  find ${folder} ! -user "${UID}" -exec chown -h "${UID}:${GID}" {} \+
-  find ${folder} ! -group "${GID}" -exec chown -h "${UID}:${GID}" {} \+
-done
 
-find /flarum ! -user "${UID}" -exec chown "${UID}:${GID}" {} \+
-find /flarum ! -group "${GID}" -exec chown "${UID}:${GID}" {} \+
+# Define the directories to set permissions on
+directories='/etc/s6.d
+/run/php
+/var/log
+/var/lib/nginx
+/flarum
+'
+
+printf '%s' "$directories" |
+  while IFS='' read -r folder; do
+  echo "[INFO] Setting permissions for ${folder}"
+  # Change ownership for files and directories not owned by ${UID}:${GID}
+  find "${folder}" \( ! -user "${UID}" -o ! -group "${GID}" \) -exec chown "${UID}:${GID}" {} \+
+
+  # List permissions for the folder and its contents
+  echo "[INFO] Permissions for ${folder}:"
+done
 
 # Set log output to STDOUT if wanted (LOG_TO_STDOUT=true)
 if [ "${LOG_TO_STDOUT}" = true ]; then
@@ -41,13 +55,16 @@ fi
 # Install additional php extensions
 if [ -n "${PHP_EXTENSIONS}" ]; then
   for php_extension in ${PHP_EXTENSIONS}; do
-    PACKAGES="php8-${php_extension} ${PACKAGES}"
+    PACKAGES="php83-${php_extension} ${PACKAGES}"
   done
   echo "[INFO] Adding php extensions"
-  apk add --no-progress --no-cache ${PACKAGES}
+  apk add --no-progress --no-cache "${PACKAGES}"
 fi
 
-cd /flarum/app
+cd /flarum/app || {
+  echo "[ERROR] Cannot cd to /flarum/app"
+  exit 1
+}
 
 # Add github token authentication (eg. for privates extensions)
 if [ "${GITHUB_TOKEN_AUTH}" != false ]; then
@@ -57,9 +74,9 @@ fi
 
 # Custom repositories (eg. for privates extensions)
 if [ -f '/flarum/app/extensions/composer.repositories.txt' ]; then
-  while read line; do
-    repository="$(echo ${line} | cut -d '|' -f1)"
-    json="$(echo ${line} | cut -d '|' -f2)"
+  while read -r line; do
+    repository="$(echo "${line}" | cut -d '|' -f1)"
+    json="$(echo "${line}" | cut -d '|' -f2)"
     echo "[INFO] Adding ${repository} composer repository"
     COMPOSER_CACHE_DIR="${CACHE_DIR}" su-exec "${UID}:${GID}" composer config repositories."${repository}" --json "${json}"
   done < /flarum/app/extensions/composer.repositories.txt
@@ -84,7 +101,7 @@ if [ -e '/flarum/app/public/assets/rev-manifest.json' ] || [ -e '/flarum/app/pub
   # Download extra extensions installed with composer wrapup script
   if [ -s "${LIST_FILE}" ]; then
     echo "[INFO] Install extra bundled extensions"
-    while read line; do
+    while read -r line; do
       extension="${extension}${line} "
     done < /flarum/app/extensions/list
     cmd="composer require ${extension}"
